version: '2.4'

volumes:
    node_modules:
      driver:
        local

services:

  frontdev:
    build:
      context: web/frontend
      args:
        - uid
        - gid
      dockerfile: Dockerfile
    command: bash -c "yarn install && yarn serve"
    volumes:
      - ./web:/app/
      - ./web/frontend/builds:/app/static_build
    ports:
      - "127.0.0.1:8080:8080"

  web:
    environment:
      WEBPACK_LOADER_ENABLED:
      VUE_DEMO_ENABLED: "True"
    depends_on:
      - frontdev
    volumes:
      - ./web/frontend/builds:/app/static_build/builds
